name: Booru
recipe: lamp
config:
  webroot: www
  xdebug: true

services:
  appserver:
    type: php:7.2 # Specify what version of php to use
    via: apache   # This could be nginx, should you choose so
    webroot: www  # Specify webroot
    config:  # If you want to add/edit
      php: ./lando/dev/php/php.ini
  database:
    type: mysql
    portforward: 3306
    creds: 
      user: mysql
      password: mysql
      database: booru
tooling:
  mysql:
    user: root
    service: database